#!/bin/bash
# Writes .claude/skills/ship/README.md, with the stage table taken from stage-table.sh.
# usage: gen-readme.sh [output-path]
set -u
D=$(cd "$(dirname "$0")/.." && pwd -P)
OUT=${1:-$D/README.md}
{
  cat <<'HEAD'
# ship

Generated by `scripts/gen-readme.sh`; do not edit. The procedure is `SKILL.md`, the model and effort
of every stage come from `scripts/effort.sh`.

## Pipeline

```
fetch -> branch (haiku) + propose (opus/high)
      -> implement -> security-gate -> simplify
      -> review, with security (gated) beside it -> fix-blockers (blockers, majors or unmet criteria)
      -> e2e (required) -> push -> pr (draft)
      -> merge-gate (waits for CI) -> HUMAN merges -> cleanup
```

Merge and closing the issue stay human. The merge gate only waits for CI through `gh pr checks`; it
never merges and never uses `--admin`. `/ship <KEY> --finish` is the person's request to mark the green PR
ready, merge it and close the issue, through `scripts/finish.sh` only. Workers run with `EDU_ORCHESTRATED=1`, so `gh-issues.sh
close-issue` refuses.

## Stages

HEAD
  bash "$D/scripts/stage-table.sh"
  cat <<'TAIL'

## Before the first run (Phase 0)

- The GitHub remote exists and `main` is pushed (the scripts diff against `origin/main`).
- Herdr is installed and Claude runs inside a Herdr pane (`HERDR_ENV` set); there is no fallback.
- The labels `in-progress`, `in-review` and `hold-merge` exist in the repo; `gh-issues.sh transition`
  fails until they do (`gh label create in-progress`, and so on).
- `.claude/opsx/` is gitignored; it holds run state.

## Checks

`bash .claude/skills/ship/scripts/test-ship.sh` runs offline, with no Herdr, gh or network.
TAIL
} > "$OUT"
HERE=$(cd "$(dirname "$0")" && pwd)
TMP=$(mktemp)
if (cd "$HERE" && pnpm -s prettier --stdin-filepath "$HERE/../README.md" < "$OUT" > "$TMP"); then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi
echo "$OUT"
