#!/bin/bash
# Writes .claude/skills/ship/README.md, with the stage table taken from stage-table.sh.
# usage: gen-readme.sh [output-path]
set -u
D=$(cd "$(dirname "$0")/.." && pwd -P)
OUT=${1:-$D/README.md}
{
  cat <<'HEAD'
# ship

Generated by `scripts/gen-readme.sh`; do not edit. The procedure is `SKILL.md`, the model and effort
of every stage come from `scripts/effort.sh`.

## Pipeline

```
fetch -> branch (haiku) + propose (opus/high)
      -> implement -> security-gate -> simplify
      -> review, with security (gated) beside it -> fix-blockers (blockers, majors or unmet criteria)
      -> e2e (required) -> push -> pr (draft)
      -> merge-gate (waits for CI) -> finish (--auto-decide, or the human's --finish; else a HUMAN merges) -> cleanup
```

The merge gate only waits for CI through `gh pr checks`; it never merges and never uses `--admin`. Merging
and closing the issue go only through `scripts/finish.sh`, which marks the green PR ready, squash-merges it and
closes the issue. An `--auto-decide` run does that itself once the gate passes (autonomous, no human gate);
otherwise it waits for a human merge, or for the person's `/ship <KEY> --finish`. `finish.sh` refuses a red,
pending, conflicting or `hold-merge` PR, so `hold-merge` is the brake. Workers run with `EDU_ORCHESTRATED=1`, so
`gh-issues.sh close-issue` refuses.

## Stages

HEAD
  bash "$D/scripts/stage-table.sh"
  cat <<'TAIL'

## Before the first run (Phase 0)

- The GitHub remote exists and `main` is pushed (the scripts diff against `origin/main`).
- Herdr is installed and Claude runs inside a Herdr pane (`HERDR_ENV` set); there is no fallback.
- The labels `in-progress`, `in-review` and `hold-merge` exist in the repo; `gh-issues.sh transition`
  fails until they do (`gh label create in-progress`, and so on).
- `.claude/opsx/` is gitignored; it holds run state.

## Checks

`bash .claude/skills/ship/scripts/test-ship.sh` runs offline, with no Herdr, gh or network.
TAIL
} > "$OUT"
HERE=$(cd "$(dirname "$0")" && pwd)
TMP=$(mktemp)
if (cd "$HERE" && pnpm -s prettier --stdin-filepath "$HERE/../README.md" < "$OUT" > "$TMP"); then mv "$TMP" "$OUT"; else rm -f "$TMP"; fi
echo "$OUT"
