
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AuditLog {
  action: string | null;
  actor_user_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  method: string | null;
  organization_id: string | null;
  path: string;
  reason: string | null;
  status: number;
}

export interface Campus {
  address: string | null;
  created_at: Generated<Timestamp>;
  organization_id: string;
  team_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ClassLevel {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  next_level_id: string | null;
  organization_id: string;
  sequence: number;
  updated_at: Generated<Timestamp>;
}

export interface FeeSchedule {
  amount_minor: Int8;
  campus_id: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  name: string;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface FileBlob {
  bytes: Buffer;
  file_id: string;
  organization_id: string;
}

export interface FileObject {
  byte_size: number;
  content_type: string;
  id: Generated<string>;
  kind: string;
  organization_id: string;
  original_name: string;
  sha256: string;
  storage_key: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string | null;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
  teamId: string | null;
}

export interface Member {
  createdAt: Timestamp;
  id: Generated<string>;
  organizationId: string;
  role: string;
  title: string | null;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface OrganizationRole {
  createdAt: Generated<Timestamp>;
  description: string | null;
  editedAt: Timestamp | null;
  id: Generated<string>;
  label: string | null;
  organizationId: string;
  permission: string;
  role: string;
  source: string | null;
  updatedAt: Timestamp | null;
}

export interface SchoolAccount {
  address: string | null;
  admission_prefix: string;
  city: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  email: string | null;
  id: Generated<string>;
  logo_file_id: string | null;
  name: string;
  organization_id: string;
  phone: string | null;
  suspended_at: Timestamp | null;
  suspended_by: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface SchoolSetting {
  created_at: Generated<Timestamp>;
  max_guardians: Generated<number>;
  organization_id: string;
  require_guardian: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Session {
  activeOrganizationId: string | null;
  activeTeamId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Student {
  admission_number: string;
  campus_id: string;
  created_at: Generated<Timestamp>;
  full_name: string;
  id: Generated<string>;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Team {
  createdAt: Timestamp;
  id: Generated<string>;
  memberCount: number;
  name: string;
  organizationId: string;
  updatedAt: Timestamp | null;
}

export interface TeamMember {
  createdAt: Timestamp | null;
  id: Generated<string>;
  membershipKey: string | null;
  teamId: string;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  mustChangePassword: Generated<boolean>;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  audit_log: AuditLog;
  campus: Campus;
  class_level: ClassLevel;
  fee_schedule: FeeSchedule;
  file_blob: FileBlob;
  file_object: FileObject;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  organizationRole: OrganizationRole;
  school_account: SchoolAccount;
  school_setting: SchoolSetting;
  session: Session;
  student: Student;
  team: Team;
  teamMember: TeamMember;
  user: User;
  verification: Verification;
}

