
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Campus {
  address: string | null;
  created_at: Generated<Timestamp>;
  organization_id: string;
  team_id: string;
  updated_at: Generated<Timestamp>;
}

export interface FeeSchedule {
  amount_minor: Int8;
  campus_id: string | null;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  name: string;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
  teamId: string | null;
}

export interface Member {
  createdAt: Timestamp;
  id: Generated<string>;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface SchoolAccount {
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  name: string;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  activeOrganizationId: string | null;
  activeTeamId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Student {
  admission_number: string;
  campus_id: string;
  created_at: Generated<Timestamp>;
  full_name: string;
  id: Generated<string>;
  organization_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Team {
  createdAt: Timestamp;
  id: Generated<string>;
  memberCount: number;
  name: string;
  organizationId: string;
  updatedAt: Timestamp | null;
}

export interface TeamMember {
  createdAt: Timestamp | null;
  id: Generated<string>;
  membershipKey: string | null;
  teamId: string;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  campus: Campus;
  fee_schedule: FeeSchedule;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  school_account: SchoolAccount;
  session: Session;
  student: Student;
  team: Team;
  teamMember: TeamMember;
  user: User;
  verification: Verification;
}

