import base, {
  noEnum,
  reactConfig,
  tailwindConfig,
} from '../../eslint.config.mjs';

const noAuth = {
  group: ['better-auth', 'better-auth/*', '@eduvault/auth-client'],
  message:
    'libs/ui is presentational; auth-aware code lives in @eduvault/auth-client.',
};
const noRadix = {
  group: ['radix-ui', 'radix-ui/*', '@radix-ui/*'],
  message:
    'Only components/ui (shadcn output) imports radix-ui; build in-house components from those primitives.',
};
const noInHouse = {
  group: ['**/custom/*', '**/lib/form-data'],
  message: 'components/ui is shadcn output and never imports in-house code.',
};

export default [
  ...base,
  ...reactConfig,
  ...tailwindConfig('src/styles/theme.css'),
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [noAuth, noRadix] }],
    },
  },
  {
    files: ['src/components/ui/**/*.tsx', 'src/hooks/**/*.ts'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [noAuth, noInHouse] }],
    },
  },
  {
    // Generated by the shadcn CLI and re-generated on `pnpm ui:add`, so these
    // rules are relaxed here instead of patching the output.
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      'no-restricted-syntax': ['error', noEnum],
      'jsx-a11y/anchor-has-content': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      'react/forbid-dom-props': 'off',
      'react/button-has-type': 'off',
      '@typescript-eslint/no-shadow': 'off',
      '@typescript-eslint/strict-boolean-expressions': 'off',
      'better-tailwindcss/enforce-canonical-classes': 'off',
      'better-tailwindcss/enforce-consistent-class-order': 'off',
      'better-tailwindcss/no-restricted-classes': 'off',
      'better-tailwindcss/no-unknown-classes': 'off',
      complexity: 'off',
      'max-lines-per-function': 'off',
      'no-param-reassign': 'off',
      'sonarjs/pseudo-random': 'off',
      'unicorn/prefer-global-this': 'off',
    },
  },
  {
    files: ['src/hooks/**/*.ts'],
    rules: {
      '@typescript-eslint/strict-boolean-expressions': 'off',
      'no-implicit-coercion': 'off',
      'unicorn/prefer-global-this': 'off',
    },
  },
];
