import base, { reactConfig } from '../../eslint.config.mjs';

const noAuth = {
  group: ['better-auth', 'better-auth/*', '@eduvault/auth-client'],
  message:
    'libs/ui is presentational; auth-aware code lives in @eduvault/auth-client.',
};
const noRadix = {
  group: ['radix-ui', 'radix-ui/*', '@radix-ui/*'],
  message:
    'Only components/ui (shadcn output) imports radix-ui; build in-house components from those primitives.',
};
const noInHouse = {
  group: ['**/custom/*', '**/lib/form-data'],
  message: 'components/ui is shadcn output and never imports in-house code.',
};

export default [
  ...base,
  ...reactConfig,
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [noAuth, noRadix] }],
    },
  },
  {
    files: ['src/components/ui/**/*.tsx', 'src/hooks/**/*.ts'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [noAuth, noInHouse] }],
    },
  },
  {
    // Generated by the shadcn CLI and re-generated on `pnpm ui:add`, so these
    // rules are relaxed here instead of patching the output.
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      'jsx-a11y/anchor-has-content': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      'react/forbid-dom-props': 'off',
      'react/button-has-type': 'off',
    },
  },
];
