/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as CampusesRouteImport } from './routes/campuses'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformSchoolsRouteImport } from './routes/platform.schools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesRoute = CampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSchoolsRoute = PlatformSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => PlatformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/campuses': typeof CampusesRoute
  '/fees': typeof FeesRoute
  '/platform': typeof PlatformRouteWithChildren
  '/students': typeof StudentsRoute
  '/dev/ui': typeof DevUiRoute
  '/platform/schools': typeof PlatformSchoolsRoute
  '/platform/': typeof PlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/campuses': typeof CampusesRoute
  '/fees': typeof FeesRoute
  '/students': typeof StudentsRoute
  '/dev/ui': typeof DevUiRoute
  '/platform/schools': typeof PlatformSchoolsRoute
  '/platform': typeof PlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/campuses': typeof CampusesRoute
  '/fees': typeof FeesRoute
  '/platform': typeof PlatformRouteWithChildren
  '/students': typeof StudentsRoute
  '/dev/ui': typeof DevUiRoute
  '/platform/schools': typeof PlatformSchoolsRoute
  '/platform/': typeof PlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/campuses'
    | '/fees'
    | '/platform'
    | '/students'
    | '/dev/ui'
    | '/platform/schools'
    | '/platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/campuses'
    | '/fees'
    | '/students'
    | '/dev/ui'
    | '/platform/schools'
    | '/platform'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/campuses'
    | '/fees'
    | '/platform'
    | '/students'
    | '/dev/ui'
    | '/platform/schools'
    | '/platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CampusesRoute: typeof CampusesRoute
  FeesRoute: typeof FeesRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  StudentsRoute: typeof StudentsRoute
  DevUiRoute: typeof DevUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses': {
      id: '/campuses'
      path: '/campuses'
      fullPath: '/campuses'
      preLoaderRoute: typeof CampusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/schools': {
      id: '/platform/schools'
      path: '/schools'
      fullPath: '/platform/schools'
      preLoaderRoute: typeof PlatformSchoolsRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface PlatformRouteChildren {
  PlatformSchoolsRoute: typeof PlatformSchoolsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformSchoolsRoute: PlatformSchoolsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  CampusesRoute: CampusesRoute,
  FeesRoute: FeesRoute,
  PlatformRoute: PlatformRouteWithChildren,
  StudentsRoute: StudentsRoute,
  DevUiRoute: DevUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
