/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as CampusesRouteImport } from './routes/campuses'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as MembersRouteImport } from './routes/members'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as MembersMemberIdRouteImport } from './routes/members_.$memberId'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformAuditRouteImport } from './routes/platform.audit'
import { Route as RolesRoleSlugRouteImport } from './routes/roles_.$roleSlug'
import { Route as RolesNewRouteImport } from './routes/roles_.new'
import { Route as PlatformSchoolsIndexRouteImport } from './routes/platform.schools.index'
import { Route as PlatformSchoolsSchoolIdRouteImport } from './routes/platform.schools.$schoolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesRoute = CampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members_/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformRoute,
} as any)
const RolesRoleSlugRoute = RolesRoleSlugRouteImport.update({
  id: '/roles_/$roleSlug',
  path: '/roles/$roleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/roles_/new',
  path: '/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSchoolsIndexRoute = PlatformSchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSchoolsSchoolIdRoute = PlatformSchoolsSchoolIdRouteImport.update({
  id: '/schools/$schoolId',
  path: '/schools/$schoolId',
  getParentRoute: () => PlatformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/campuses': typeof CampusesRoute
  '/fees': typeof FeesRoute
  '/members': typeof MembersRoute
  '/platform': typeof PlatformRouteWithChildren
  '/roles': typeof RolesRoute
  '/students': typeof StudentsRoute
  '/dev/ui': typeof DevUiRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/roles/$roleSlug': typeof RolesRoleSlugRoute
  '/roles/new': typeof RolesNewRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/schools/$schoolId': typeof PlatformSchoolsSchoolIdRoute
  '/platform/schools/': typeof PlatformSchoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/campuses': typeof CampusesRoute
  '/fees': typeof FeesRoute
  '/members': typeof MembersRoute
  '/roles': typeof RolesRoute
  '/students': typeof StudentsRoute
  '/dev/ui': typeof DevUiRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/roles/$roleSlug': typeof RolesRoleSlugRoute
  '/roles/new': typeof RolesNewRoute
  '/platform': typeof PlatformIndexRoute
  '/platform/schools/$schoolId': typeof PlatformSchoolsSchoolIdRoute
  '/platform/schools': typeof PlatformSchoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/campuses': typeof CampusesRoute
  '/fees': typeof FeesRoute
  '/members': typeof MembersRoute
  '/platform': typeof PlatformRouteWithChildren
  '/roles': typeof RolesRoute
  '/students': typeof StudentsRoute
  '/dev/ui': typeof DevUiRoute
  '/members_/$memberId': typeof MembersMemberIdRoute
  '/platform/audit': typeof PlatformAuditRoute
  '/roles_/$roleSlug': typeof RolesRoleSlugRoute
  '/roles_/new': typeof RolesNewRoute
  '/platform/': typeof PlatformIndexRoute
  '/platform/schools/$schoolId': typeof PlatformSchoolsSchoolIdRoute
  '/platform/schools/': typeof PlatformSchoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/campuses'
    | '/fees'
    | '/members'
    | '/platform'
    | '/roles'
    | '/students'
    | '/dev/ui'
    | '/members/$memberId'
    | '/platform/audit'
    | '/roles/$roleSlug'
    | '/roles/new'
    | '/platform/'
    | '/platform/schools/$schoolId'
    | '/platform/schools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/campuses'
    | '/fees'
    | '/members'
    | '/roles'
    | '/students'
    | '/dev/ui'
    | '/members/$memberId'
    | '/platform/audit'
    | '/roles/$roleSlug'
    | '/roles/new'
    | '/platform'
    | '/platform/schools/$schoolId'
    | '/platform/schools'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/campuses'
    | '/fees'
    | '/members'
    | '/platform'
    | '/roles'
    | '/students'
    | '/dev/ui'
    | '/members_/$memberId'
    | '/platform/audit'
    | '/roles_/$roleSlug'
    | '/roles_/new'
    | '/platform/'
    | '/platform/schools/$schoolId'
    | '/platform/schools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CampusesRoute: typeof CampusesRoute
  FeesRoute: typeof FeesRoute
  MembersRoute: typeof MembersRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  RolesRoute: typeof RolesRoute
  StudentsRoute: typeof StudentsRoute
  DevUiRoute: typeof DevUiRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  RolesRoleSlugRoute: typeof RolesRoleSlugRoute
  RolesNewRoute: typeof RolesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses': {
      id: '/campuses'
      path: '/campuses'
      fullPath: '/campuses'
      preLoaderRoute: typeof CampusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members_/$memberId': {
      id: '/members_/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/audit': {
      id: '/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/roles_/$roleSlug': {
      id: '/roles_/$roleSlug'
      path: '/roles/$roleSlug'
      fullPath: '/roles/$roleSlug'
      preLoaderRoute: typeof RolesRoleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles_/new': {
      id: '/roles_/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/schools/': {
      id: '/platform/schools/'
      path: '/schools'
      fullPath: '/platform/schools/'
      preLoaderRoute: typeof PlatformSchoolsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/schools/$schoolId': {
      id: '/platform/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/platform/schools/$schoolId'
      preLoaderRoute: typeof PlatformSchoolsSchoolIdRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface PlatformRouteChildren {
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformSchoolsSchoolIdRoute: typeof PlatformSchoolsSchoolIdRoute
  PlatformSchoolsIndexRoute: typeof PlatformSchoolsIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformSchoolsSchoolIdRoute: PlatformSchoolsSchoolIdRoute,
  PlatformSchoolsIndexRoute: PlatformSchoolsIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  CampusesRoute: CampusesRoute,
  FeesRoute: FeesRoute,
  MembersRoute: MembersRoute,
  PlatformRoute: PlatformRouteWithChildren,
  RolesRoute: RolesRoute,
  StudentsRoute: StudentsRoute,
  DevUiRoute: DevUiRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  RolesRoleSlugRoute: RolesRoleSlugRoute,
  RolesNewRoute: RolesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
